[build]
  command = "npm run build:web"
  publish = "web/dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://tu-backend-url.herokuapp.com/api/:splat"
  status = 200

[[redirects]]
  from = "/panel"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/app"
  to = "/app-movil-funcional.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
